version: '3.9'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: orbslam
    platform: linux/arm64
    container_name: orbslam-dev
    stdin_open: true
    tty: true
    command: bash
    cap_add:
      - "SYS_PTRACE"
    environment:
      - DISPLAY=host.docker.internal:0
      - ROS_IP=127.0.0.1
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/bags:/bags
      - ${HOME}/datasets:/datasets
      - workspaces:/workspaces
  postgres:
    image: kartoza/postgis:15-3
    platform: linux/arm64
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  pg_data:
  workspaces:
